---
- hosts: localhost 
  become: yes
  tasks:
  - name: install apache
    yum:
      name: httpd
      state: present
  - name: start and enable service
    service:
      name: httpd
      state: started
  - name: copy home page
    template:
      src: apache.j2
      dest: /var/www/html/index.html
    notify: restart
  handlers:
  - name: restart
    service:
      name: httpd
      state: restarted 
   
      
  
